# Generated by Django 4.2.4 on 2023-11-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='correo_electronico',
            field=models.EmailField(max_length=254),
        ),
    ]
