# Generated by Django 4.2.4 on 2023-12-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios_app', '0003_socio_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
